app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, IntegerField, TextAreaField
from ..validators import mainValidators

class DebtConfirmation(FlaskForm):
    accept = SubmitField('Accept')
    reject = SubmitField('Reject')

class CreateDebt(FlaskForm):
    debtTo = StringField('Debt to')
    total = IntegerField('Total', validators=[mainValidators.IntegerRequired])
    description = TextAreaField('Description')
    create = SubmitField('Create')

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, errors

app/main/views.py
from flask import render_template, redirect, url_for, request, flash
from flask_login import current_user, logout_user
from .forms import DebtConfirmation, CreateDebt
from ..models import Debt, User
from ..basicFunctions.mainFunctions import *
from ..validators.mainValidators import pure
from . import main

from wtforms import ValidationError
import datetime

# Only authorized users can access this Blueprint
@main.before_request
def restrictMain():
    if not current_user.is_authenticated or \
       not current_user._get_current_object().confirmedAccount:
        flash('You must log in')
        return redirect(url_for('auth.main'))

    if not 'pver' in request.cookies or \
       request.cookies.get('pver') != current_user._get_current_object().password_ver:
        flash('You must log in')
        logout_user()
        return redirect(url_for('auth.main'))

# Main page: last 20 debts + totalDebt
# TODO: In rows 19, 20 change a lot of filter_by with one request
@main.route('/')
def main_route():
    user = current_user._get_current_object()
    gave = user.give.order_by(Debt.id.desc()).filter_by(confirmed=True).filter_by(refused=False).filter_by(paid=False).limit(15).all()
    ret = user.ret.order_by(Debt.id.desc()).filter_by(confirmed=True).filter_by(refused=False).filter_by(paid=False).limit(15).all()

    debts = []
    for debt in gave:
        debts.append([-debt.id, debt.total, debt.ret.username, debt.about])

    for debt in ret:
        debts.append([-debt.id, -debt.total, debt.give.username, debt.about])

    debts.sort()
    
    if len(debts) > 15:
        debts = debts[:15]

    #TODO: Not use sort. Go throw gave and ret at the same time
    
    return render_template('main/main.html', totalDebt=user.totalDebt, debts=debts,
     notConfirmedTotalDebt=user.notConfirmedTotalDebt)

# Page which displays debt for confirmation
@main.route('/confirm/<page>')
def confirm(page = 0):
    user = current_user._get_current_object()

    try:
        page = int(page)
    except:
        return redirect(url_for('main.confirm', page=0))

    if page < 0:
        return redirect(url_for('main.confirm', page=0))

    if page != 0 and (page - 1) * 15 >= user.notConfirmedAmount:
        return redirect(url_for('main.confirm', page=0))

    debts = user.ret.filter_by(confirmed=False).order_by(Debt.id.desc()) \
            .limit(15).offset(page * 15).all()
    
    return render_template('/main/confirm.html', debts=debts, page=page)

# Page for confirmation debt
@main.route('/confirm_debt/<int:id>')
def confirm_debt(id):
    debt = Debt.query.get(id)
    user = current_user._get_current_object()
    
    if not debt:
        flash('Error: no debt found')
        return redirect(url_for('main.confirm', page=0))

    if not confirmDebt(user, debt):
        flash('Error: can\'t confirm debt')
        return redirect(url_for('main.confirm', page=0))
    
    return redirect(url_for('main.confirm', page=0))
    
# Page for rejecting debt
@main.route('/reject_debt/<int:id>')
def reject_debt(id):
    debt = Debt.query.get(id)
    user = current_user._get_current_object()
    
    if not debt:
        flash('Error: no debt found')
        return redirect(url_for('main.confirm', page=0))

    if not rejectDebt(user, debt):
        flash('Error: can\'t reject debt')
        return redirect(url_for('main.confirm', page=0))
    
    return redirect(url_for('main.confirm', page=0))

@main.route('/pay_debt/<int:id>')
def pay_debt(id):
    debt = Debt.query.get(id)
    user = current_user._get_current_object()

    if not debt:
        flash('Error: no debt found')
        return redirect(url_for('main.lended', page=0))

    if not payDebt(user, debt):
        flash('Error: can\'t reject debt')
        return redirect(url_for('main.lended', page=0))

    return redirect(url_for('main.lended', page=0))

# Page for creating debt
@main.route('/give', methods=['GET', 'POST'])
def create():
    createForm = CreateDebt(request.form)

    if request.method == 'POST' and createForm.validate():

        if len(createForm.debtTo.data) > 17:
            createForm.debtTo.errors += (ValidationError("No user with this username"),)
            return render_template('/main/create.html', form=createForm)

        if len(createForm.description.data) > 150:
            createForm.description.errors += (ValidationError("Your description is longer 150"))
            return render_template('/main/create.html', form=createForm)

        user = current_user._get_current_object()
        userTo = User.query.filter_by(username=str(createForm.debtTo.data)).first()
        if not userTo:
            createForm.debtTo.errors += (ValidationError("No user with this username"),)
            return render_template('/main/create.html', form=createForm)

        if user == userTo:
            createForm.debtTo.errors += (ValidationError("You can't lend yourself"),)
            return render_template('/main/create.html', form=createForm)

        if user.debtsLeft == 0:
            flash("You have too many debts")
            return render_template('/main/create.html', form=createForm)


        total = int(createForm.total.data)

        if total <= 0:
            createForm.total.errors += (ValidationError("You can't lend < 0"),)
            return render_template('/main/create.html', form=createForm)

        description = pure(str(createForm.description.data))

        createDebt(user, userTo, total, description)

        return redirect(url_for('main.main_route'))

    return render_template('/main/create.html', form=createForm)

# Page for taking money
@main.route('/take', methods=['POST', 'GET'])
def take():
    createForm = CreateDebt(request.form)

    if request.method == 'POST' and createForm.validate():

        if len(createForm.debtTo.data) > 17:
            createForm.debtTo.errors += (ValidationError("No user with this username"),)
            return render_template('/main/create.html', form=createForm)

        if len(createForm.description.data) > 150:
            createForm.description.errors += (ValidationError("Your description is longer 150"))
            return render_template('/main/create.html', form=createForm)

        user = current_user._get_current_object()
        userFrom = User.query.filter_by(username=str(createForm.debtTo.data)).first()
        if not userFrom:
            createForm.debtTo.errors += (ValidationError("No user with this username"),)
            return render_template('/main/create.html', form=createForm)

        if user == userFrom:
            createForm.debtTo.errors += (ValidationError("You can't lend yourself"),)
            return render_template('/main/create.html', form=createForm)

        if userFrom.debtsLeft == 0:
            flash("You have too many debts")
            return render_template('/main/create.html', form=createForm)


        total = int(createForm.total.data)

        if total <= 0:
            createForm.total.errors += (ValidationError("You can't lend < 0"),)
            return render_template('/main/create.html', form=createForm)

        description = pure(str(createForm.description.data))

        createDebt(userFrom, user, total, description, isConfirmed=True)

        return redirect(url_for('main.main_route'))

    return render_template('/main/create.html', form=createForm)

# Page for given money
@main.route('/lended/<page>', methods=['GET', 'POST'])
def lended(page = 0):
    user = current_user._get_current_object()

    try:
        page = int(page)
    except:
        return redirect(url_for('main.lended', page=0))

    if page < 0:
        return redirect(url_for('main.lended', page=0))
    
    if page != 0 and (page - 1) * 15 >= user.giveAmount:
        return redirect(url_for('main.lended', page=0))
    

    gave = user.give.order_by(Debt.id.desc()).limit(15).offset(15 * page).all()

    return render_template('/main/lended.html', gave=gave, page=page)


# Page for taken money
@main.route('/borrowed/<page>', methods=['GET', 'POST'])
def borrowed(page = 0):
    user = current_user._get_current_object()

    try:
        page = int(page)
    except:
        return redirect(url_for('main.borrowed', page=0))

    if page < 0:
        return redirect(url_for('main.borrowed', page=0))

    if page != 0 and (page - 1) * 15 >= user.retAmount:
        return redirect(url_for('main.borrowed', page=0))

    ret = user.ret.order_by(Debt.id.desc()).offset(15 * page).limit(15).all()

    return render_template('/main/borrowed.html', ret=ret, page=page)

app/templates/main/borrowed.html
{% extends 'main/main-base.html' %}

{% block content %}
    {% if ret|length > 0 %}
        <div class="main-debts">
            {% for debt in ret %}
                {{show_debt(debt)}}
            {% endfor %}
            <div class="navigation">
                {% if page != 0 %} 
                    <a href="{{url_for('main.borrowed', page=page-1)}}"> 
                {% endif %}
                        <span class="material-icons">
                            navigate_before
                        </span>
                {% if page != 0 %} 
                    </a> 
                {% endif %}

                {% if (page + 1) * 15 < current_user.retAmount %}
                    <a href="{{url_for('main.borrowed', page=page+1)}}">
                {% endif %}
                        <span class="material-icons">
                            navigate_next
                        </span>
                {% if (page + 1) * 15 < current_user.retAmount %}
                    </a>
                {% endif %}
            </div>
        </div>
    {% else %}
        <h1>Empty</h1>
        <p>You have no borrowed debts</p>
    {% endif %}
{% endblock %}

app/templates/main/confirm.html
{% extends 'main/main-base.html' %}

{% block content %}
    
    {% if debts|length > 0 %}
        <div class="main-debts">
            {% for debt in debts %}
                {{show_debt(debt)}}
            {% endfor %}
            <div class="navigation">
                {% if page != 0 %} 
                    <a href="{{url_for('main.confirm', page=page-1)}}"> 
                {% endif %}
                        <span class="material-icons">
                            navigate_before
                        </span>
                {% if page != 0 %} 
                    </a> 
                {% endif %}

                {% if (page + 1) * 15 < current_user.notConfirmedAmount %}
                    <a href="{{url_for('main.confirm', page=page+1)}}">
                {% endif %}
                        <span class="material-icons">
                            navigate_next
                        </span>
                {% if (page + 1) * 15 < current_user.notConfirmedAmount %}
                    </a>
                {% endif %}
            </div>
        </div>
    {% else %}
        <h1>Empty</h1>
        <p>You have no unconfirmed debts</p>
    {% endif %}
    
{% endblock %}

app/templates/main/create.html
{% extends 'main/main-base.html' %}
{% from '_macros.html' import show_field %}

{% block content %}
    <div class="form">
        <form action="{{url_for(request.endpoint)}}" method="POST">
                {{form.csrf_token}}

            <div>
                {{show_field('name', form.debtTo)}}
            </div>

            <div>
                {{show_field('total', form.total)}}
            </div>

            <div>
                {{show_field('description', form.description)}}
            </div>

            <div class="submit">
                {{form.create}}
            </div>
        </form>
    </div>
{% endblock %}

app/templates/main/lended.html
{% extends 'main/main-base.html' %}

{#Can optimize code#}

{% block content %}
    {% if gave|length > 0 %}
        <div class="main-debts">
            {% for debt in gave %}
                {{show_debt(debt)}}
            {% endfor %}
            <div class="navigation">
                {% if page != 0 %} 
                    <a href="{{url_for('main.lended', page=page-1)}}"> 
                {% endif %}
                        <span class="material-icons">
                            navigate_before
                        </span>
                {% if page != 0 %} 
                    </a> 
                {% endif %}

                {% if (page + 1) * 15 < current_user.giveAmount %}
                    <a href="{{url_for('main.lended', page=page+1)}}">
                {% endif %}
                        <span class="material-icons">
                            navigate_next
                        </span>
                {% if (page + 1) * 15 < current_user.giveAmount %}
                    </a>
                {% endif %}
            </div>
        </div>
    {% else %}
        <h1>Empty</h1>
        <p>You have no lended debts</p>
    {% endif %}
{% endblock %}

app/templates/main/main-base.html
{% extends 'base.html' %}
{% from '_macros.html' import show_debt with context %}

{% block sideMenu %}
    <div class="side-link main-link"> <a href="{{url_for('main.main_route')}}"> Main </a></div>
    <div class="side-link"> <a href="{{url_for('main.confirm', page=0)}}">Confirm</a> </div>
    <div class="side-link"> <a href="{{url_for('main.create')}}">Give</a> </div>
    <div class="side-link"> <a href="{{url_for('main.take')}}">Take</a> </div>
    <div class="side-link"> <a href="{{url_for('main.lended', page=0)}}">Given</a> </div>
    <div class="side-link"> <a href="{{url_for('main.borrowed', page=0)}}">Taken</a> </div>
{% endblock %}

app/templates/main/main.html
{% extends 'main/main-base.html' %}
{% block content %}
        <div class="main-debts">
            <div class="total_debt">
                <span class="{% if totalDebt >= 0 %}give{% else %}ret{% endif %}">{{totalDebt}}₽</span>
            </div>
            <div class="not_confirmed_total">
                <span class="mobile-hide">not confirmed: </span>{{notConfirmedTotalDebt}}₽
            </div>
        </div>
        {% if debts|length == 0 %}
            <div class="debt-row" style="text-align: center;">
                <h1>Empty</h1>
                <p>You have no active debts</p>
            </div>
        {% else %}
            {% for debt in debts %}
                <div class="debt_row">
                    {% if debt[1] >= 0 %}
                        <div class="green-font material-icons">
                            vertical_align_top
                        </div>
                    {% else %}
                        <div class="green-font material-icons">
                            vertical_align_bottom
                        </div>
                    {% endif %}

                    <span>{{debt[1]|abs}}₽ - {{debt[2]}}</span>

                    <span style="float:right;" class="full-button" onclick="showDescription(this)">
                        <span class="material-icons">
                            keyboard_arrow_down
                        </span>
                    </span>
                    <div class="description hidden">
                        {{debt[3]}}
                    </div>
                </div>
            {% endfor %}
        {% endif %}
{% endblock %}